# loops

# program to print first number divisible by 5

In [12]:
nums = [12,45,67,25,89]
for i in range(len(nums)):
    if nums[i]%5==0:
        print(nums[i])
        break
else:
    print("There is no number divisible by 5")

45


# program to check prime number

In [18]:
num = int(input("Enter a number"))
for i in range(2,num//2):
    if num%i==0:
        print("Number is not prime")
        break
else:
    print("Number is prime")

Enter a number11
Number is prime


# Arrays

In [24]:
import array as arr
vals = arr.array('i',[4,5,-8,9,-98])
print(vals)

array('i', [4, 5, -8, 9, -98])


In [25]:
import array as arr
vals = arr.array('I',[4,5,8,9,10])
print(vals)

array('I', [4, 5, 8, 9, 10])


In [27]:
from array import *
vals = array('u',['c','a','h','j'])
print(vals)

array('u', 'cahj')


In [30]:
from array import *
vals = array('u',['v','h','b','j'])
print(vals)

array('u', 'vhbj')


In [36]:
import array as arr
vals = arr.array('f',[4.98,5,-8,9,10])
print(vals)
print(len(vals))

array('f', [4.980000019073486, 5.0, -8.0, 9.0, 10.0])
5


In [39]:
import array as arr
vals = arr.array('d',[4.98,5,8,9,10])
print(vals)

array('d', [4.98, 5.0, 8.0, 9.0, 10.0])


In [46]:
import array as arr
vals = arr.array('d',[4.98,5,8,9,10])
print(vals)
print(vals.typecode)
print(vals.buffer_info()) #tells address and size 

array('d', [4.98, 5.0, 8.0, 9.0, 10.0])
d
(129233904, 5)


In [76]:
import array as arr
vals = arr.array('d',[4.98,5,8,9,10])
print(vals)
vals.reverse()
print(vals)
vals.remove(8)  #parameter is the value to be deleted
print(vals)
vals.append(30)
print(vals)
print(vals.index(5))
vals.insert(1,59)
print(vals)
del vals[2]    # parameter is the index of which element to be deleted
print(vals)

array('d', [4.98, 5.0, 8.0, 9.0, 10.0])
array('d', [10.0, 9.0, 8.0, 5.0, 4.98])
array('d', [10.0, 9.0, 5.0, 4.98])
array('d', [10.0, 9.0, 5.0, 4.98, 30.0])
2
array('d', [10.0, 59.0, 9.0, 5.0, 4.98, 30.0])
array('d', [10.0, 59.0, 5.0, 4.98, 30.0])


In [65]:
from array import *
marks = array('i',[3,7,8,9,24])
for m in marks:
    print(m)
print()
for i in range(len(marks)):
    print(marks[i])
print()    
k=0
while(k<len(marks)):
    print(marks[k])
    k+=1

3
7
8
9
24

3
7
8
9
24

3
7
8
9
24


In [63]:
from array import *
vals = array('i',[2,4,3,5])
newArr = array(vals.typecode ,( a for a in vals))
for e in newArr:
    print(e)

2
4
3
5


In [64]:
from array import *
vals = array('i',[2,4,3,5])
newArr = array(vals.typecode ,( a*a for a in vals))
for e in newArr:
    print(e)

4
16
9
25


# Asking values from user to input

In [74]:
from array import *
arr = array('i',[])
n = int(input("Enter the number of elements of array "))
for i in range(n):
    x = int(input("Enter value "))
    arr.append(x)
print(arr)
element = int(input("which element do u want to search "))

for i in range(len(arr)):
    if arr[i]==element:
        print(i)
        break
else:
    print("Element " ,element ," does not exist")

print(arr.index(element))

Enter the number of elements of array 5
Enter value 2
Enter value 4
Enter value 67
Enter value 8
Enter value 90
array('i', [2, 4, 67, 8, 90])
which element do u want to search 90 
4
4


In [79]:
from array import *
arr = array('i',[[2,3,4],[6,7,9]]) #from array can not make 2d array

TypeError: an integer is required (got type list)

# numpy package

In [83]:
from numpy import *
arr = array([2,5,6,8])
print(arr)

[2 5 6 8]


In [93]:
from numpy import *
arr = array([2,5,6,8],float)
print(arr)
print(arr.dtype)

[ 2.  5.  6.  8.]
float64


In [87]:
from numpy import *
arr = array([2,5,6,8],int)
print(arr)

[2 5 6 8]


In [92]:
from numpy import *
arr = array([[2,5,6,8],[3,55,7,8]],int)
print(arr)

[[ 2  5  6  8]
 [ 3 55  7  8]]


In [96]:
from numpy import *
arr = linspace(0,16,5) #start,end,No of parts to be broken
print(arr)

[  0.   4.   8.  12.  16.]


In [97]:
from numpy import *
arr = arange(0,15,2) #start,end,step
print(arr)

[ 0  2  4  6  8 10 12 14]


In [101]:
from numpy import *
arr = zeros(5)
print(arr)

[ 0.  0.  0.  0.  0.]


In [102]:
from numpy import *
arr = zeros(5,int)
print(arr)

[0 0 0 0 0]


In [104]:
from numpy import *
arr = ones(5)
print(arr)

[ 1.  1.  1.  1.  1.]


In [105]:
from numpy import *
arr = ones(5,int)
print(arr)

[1 1 1 1 1]


In [131]:
from numpy import *
arr1 = array([3,4,5,6])
print(arr1)

arr1+=5

print(arr1)
print(min(arr1))
# print(max(arr1))
print(sum(arr1))
print(sin(arr1))
print(cos(arr1))
print(log(arr1))
print(sqrt(arr1))

arr2 = array([5,7,3,8])
print(arr2)
arr3 = arr1 + arr2
print(arr3)

print(concatenate([arr1,arr2]))

[3 4 5 6]
[ 8  9 10 11]
8
38
[ 0.98935825  0.41211849 -0.54402111 -0.99999021]
[-0.14550003 -0.91113026 -0.83907153  0.0044257 ]
[ 2.07944154  2.19722458  2.30258509  2.39789527]
[ 2.82842712  3.          3.16227766  3.31662479]
[5 7 3 8]
[13 16 13 19]
[ 8  9 10 11  5  7  3  8]


# Shallow copy and Deep copy

In [136]:
from numpy import *
arr1 = array([2,4,5,67,9])
arr2 = arr1      # these are only aliases
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
print("after view")  # shallow copy
arr2 = arr1.view()
arr1[1] =50
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

arr2 = arr1.copy()  #deep copy
arr1[1] =60
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))


[ 2  4  5 67  9]
[ 2  4  5 67  9]
129773440
129773440
after view
[ 2 50  5 67  9]
[ 2 50  5 67  9]
129773440
129773120
[ 2 60  5 67  9]
[ 2 50  5 67  9]
129773440
129974560


# Array Functions

In [9]:
from numpy import *
arr = array([[2,5,6,8],[3,55,7,8]])
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)

arr2 = arr.flatten()
print(arr2)

print(arr2.reshape(4,2))

[[ 2  5  6  8]
 [ 3 55  7  8]]
int32
2
(2, 4)
8
[ 2  5  6  8  3 55  7  8]
[[ 2  5]
 [ 6  8]
 [ 3 55]
 [ 7  8]]


# Matrix Function 

In [18]:
from numpy import *
m = matrix('1 2 3;4 5 6; 9 8 2')
print(m)
print("diagonal of matrix " , diagonal(m))
print("min value " , m.min())
print("max value " , m.max())
print("sum  " , m.sum())

[[1 2 3]
 [4 5 6]
 [9 8 2]]
diagonal of matrix  [1 5 2]
min value  1
max value  9
sum   40


# Matrix operations

In [24]:
from numpy import *
m1 = matrix('1 2 3 ; 4 5 6 ; 9 8 2')
m2 = matrix('3 2 5 ; 6 8 9 ; 2 4 6')
print("Matrix 1 is")
print(m1)
print("Matrix 2 is")
print(m2)
print("Matrix sum is")
m3 = m1+m2
print(m3)
print("Matrix diff  is")
m3 =m1-m2
print(m3)
print("Matrix multiplication is")
m3 = m1*m2
print(m3)
print("Matrix Division is")
m3 = m1/m2
print(m3)

Matrix 1 is
[[1 2 3]
 [4 5 6]
 [9 8 2]]
Matrix 2 is
[[3 2 5]
 [6 8 9]
 [2 4 6]]
Matrix sum is
[[ 4  4  8]
 [10 13 15]
 [11 12  8]]
Matrix diff  is
[[-2  0 -2]
 [-2 -3 -3]
 [ 7  4 -4]]
Matrix multiplication is
[[ 21  30  41]
 [ 54  72 101]
 [ 79  90 129]]
Matrix Division is
[[ 0.33333333  1.          0.6       ]
 [ 0.66666667  0.625       0.66666667]
 [ 4.5         2.          0.33333333]]



# Functions

In [9]:
def sum(a,b,c):
    return a+b+c
sum(3,5,6)

14

In [10]:
def sum(a,b):
    s= a+b
    return s
sum(3,6)

9

# Returning multiple values from function

In [25]:
def sum_sub(a,b):
    return a+b , a-b
print(sum_sub(3,4))

(7, -1)


In [12]:
def sum(a,*b):
    s=a
    for num in b:
        s+=num
    return s
sum(3,5,6,7,3,8)

32

In [16]:
def person(name,age=18):
    print(name,age)
person("vaishali",22)

vaishali 22


# Positional Argument

In [43]:
def person(name,age=18):
    print(name,age-5)
person(age = 22,name= "vaishali")

vaishali 17


# Default argument

In [19]:
def person(name,marks,age=18):
    print(name,age,marks)
person("vaishali",50)

vaishali 18 50


In [54]:
def person(name,*data):
    print(name,data)
person(18,9953030,"mumbai")

18 (9953030, 'mumbai')


In [56]:
def person(name,**data):
    print(name,data)
person("vaishali",age = 18,mobile = 9953030,city = "mumbai")

vaishali {'age': 18, 'mobile': 9953030, 'city': 'mumbai'}


In [60]:
def person(name,**data):
    print(name)
    
    for i,j in data.items():
        print(i,j)
        
person("vaishali",age = 18,mobile = 9953030856,city = "mumbai")

vaishali
age 18
mobile 9953030856
city mumbai


# variable list and String passed as argument in function

In [26]:
def update(x):
    x=8
    print(x)
update(10)

8


In [31]:
def update(x):
    print("in func before updating " , id(x))
    x=8
    print("in func after updating " , id(x))
    print("x " , x)
a=10
print("address of a" , id(a))
update(a)
print("a " , a)

address of a 1957454272
in func before updating  1957454272
in func after updating  1957454208
x  8
a  10


In [34]:
def update(lst1):
    print("in func before updating " , id(lst1))
    lst1[1] = 25
    print("in func after updating " , id(lst1))  #lst are mutable
    print("lst1 " , lst1)
lst=[10,30,49]
print("address of a" , id(lst))
update(lst)
print("lst " , lst)

address of a 115603400
in func before updating  115603400
in func after updating  115603400
lst1  [10, 25, 49]
lst  [10, 25, 49]


In [39]:
def update(s1):
    print("in func before updating " , id(s1))
    s1[0] ="n"                                 #strings  are immutable
    print("in func after updating " , id(s1))  
    print("s1 " , s1)
s = "vaishali"
print("address of s" , id(s))
update(s)
print("s " , s)

address of s 115661168
in func before updating  115661168


TypeError: 'str' object does not support item assignment

# Global and Local variable

In [63]:
a=10
def checking():
    a=20
    print("in func" , a)
checking()
print("outside" ,a)

in func 20
outside 10


# Global variable

In [67]:
a=10
print(id(a))
def checking():
    x= globals()['a']
    print(id(x))
    globals()['a'] = 15  #changing the the value of global variable without affecting local variable
    a=20
    print("in func" , a)

checking()
print("outside" ,a)

1957454272
1957454272
in func 20
outside 15


# Find No of even and odd numbers in list

In [74]:
lst = [2,4,3,6,8,9]
def find_even_odd(l):
    even = odd =0
    for i in l:
        if i%2==0:
            even+=1
        else:
            odd+=1
    return even,odd
even,odd = find_even_odd(lst)
print(even,odd)
print("Even: {} and odd: {}" .format(even,odd))
print("Even:" ,even , "and odd " ,odd)

4 2
Even: 4 and odd: 2
Even: 4 and odd  2


# Fibonaaci Series

In [78]:
def fibonacci(n):
    a=0
    b=1
    print(a)
    print(b)
    for i in range(0,n-2):
        c=a+b
        print(c)
        a=b
        b=c
fibonacci(8)

0
1
1
2
3
5
8
13


# Factorial Function

In [82]:
def fact(n):
    f=1
    for i in range(2,n+1):
       f*=i
    return f
fact(5)

120

# Recursive factorial funaction

In [83]:
def fact(n):
    if(n==0):
        return 1
    else:
        return n*fact(n-1)
fact(4)

24

# Anonymus Function

In [1]:
f= lambda a,b : a + b
result = f(3,6)
print(result)

9


In [7]:
from functools import reduce
nums = [2,3,5,1,7,8,4,10]
evens = list(filter(lambda n: n%2==0,nums))
print(evens)
doubles = list(map(lambda n:n*2,evens))
print(doubles)
sum = reduce(lambda a,b:a+b , doubles)
print(sum)

[2, 8, 4, 10]
[4, 16, 8, 20]
48


# class - Objects - oops concepts

In [1]:
class A:
    def __init__(self,v):
        self.v=v
    def first(self):
        print("First function")
a= A(10)
a.first()
print(a.v)

First function
10
